/* autogenerated by Processing revision 1282 on 2022-04-23 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;
import processing.video.*;
import java.util.TimerTask;
import java.util.Timer;
import java.util.Date;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class TP2KathyPoirier extends PApplet {







ParticleSystem ps;

PFont typo;

SoundFile fantasySong;
Movie intro;
SoundFile AudioFortune;
SoundFile AudioAmour;
SoundFile AudioCarriere;

 float biscuitPositionX;
 float biscuitPositionY;
 float biscuitWidth;
 float biscuitHeight;
 float biscuitScaleUp;
 float biscuitScaleDown;
 float biscuitMinX;
 float biscuitMinY;
 float biscuitMaxX;
 float biscuitMaxY;
 
float timelineDuration = 10.0f;

float timeScale = 1.0f;
float timeScaleMin = 0.25f;
float timeScaleMax = 100.0f;
float timeScaleDelta = 0.25f;

float offsetHorizontal = 64.0f;

float timelinePlayhead;
float timelinePlayheadPosition;

float timelinePositionStartX;
float timelinePositionStartY;
float timelinePositionEndX;
float timelinePositionEndY;
float timelinePositionDelta;
float timelineMarkerHalfSize;

float timeNow;
float timeLast;
float timeElapsed;

String Titre = "titre.png";
String BiscuitFortuneGauche = "biscuitfortune01.png";
String BiscuitFortuneDroite = "biscuitfortune02.png";
String BiscuitAmourGauche = "biscuitamour01.png";
String BiscuitAmourDroite = "biscuitamour02.png";

JSONObject json;

String videoFile;
String musicFile;
String audioFile01;
String audioFile02;
String audioFile03;

boolean playVideo = true;
boolean isOverBiscuit;
boolean isBiscuitPressed;
boolean showBiscuit = true; 
boolean isTimelineActive = true;

int savedTime;
int totalTime = 6000;
PImage imgTitre;
PImage imgBiscuitFortuneGauche;
PImage imgBiscuitFortuneDroite;
PImage imgBiscuitAmourGauche;
PImage imgBiscuitAmourDroite;


String[] words = {"bonne chance", "célèbre la vie", "allume une chandelle",  "masse ton 3e oeil", "quelqu'un pense à toi", "le succès s'en vient", "oui mais non","sors dehors", "pourquoi pas?", "danse", "l'alignement des astres est en ta faveur", "écris à ton.ta crush", "on t'envoie des ondes positives", "ça pourrait aller mieux", "mange plus de légumes", "inspire, expire" };
String currentWord = "";

 public void setup()
{ 
 
  readConfig();
   
  /* size commented out by preprocessor */;
  frameRate(60);
  textAlign(CENTER,CENTER);
  textSize(36);
  
  typo = loadFont("STYuanti-SC-Regular-48.vlw");
  
  textFont(typo);
  
  timeNow = timeLast = timeElapsed = 0.0f;

  timelinePlayhead = 0.0f;

  timelinePositionStartX = offsetHorizontal;
  timelinePositionStartY = height - height/3 + 45 ;
  timelinePositionEndX = width - offsetHorizontal;
  timelinePositionEndY = timelinePositionStartY;
  timelinePositionDelta = timelinePositionEndX - timelinePositionStartX;
  timelineMarkerHalfSize = 32.0f;
  
  ps = new ParticleSystem(new PVector(width/2, 85));
  

  fantasySong = new SoundFile(this, musicFile);
  fantasySong.play();
  
  AudioFortune = new SoundFile(this, audioFile01);
  AudioAmour = new SoundFile(this, audioFile02);
  AudioCarriere = new SoundFile(this, audioFile03);

 imgTitre = loadImage(Titre);
 imgBiscuitFortuneGauche = loadImage(BiscuitFortuneGauche);
 imgBiscuitFortuneDroite = loadImage(BiscuitFortuneDroite);
 imgBiscuitAmourGauche = loadImage(BiscuitAmourGauche);
 imgBiscuitAmourDroite = loadImage(BiscuitAmourDroite);

 
 biscuitPositionX = width / 2.0f;
 biscuitPositionY = height / 2.0f;
 biscuitWidth = width * 0.5f;
 biscuitHeight = height * 0.3f;
 biscuitScaleUp = 1.05f;
 biscuitScaleDown = 0.95f;
 biscuitMinX = biscuitPositionX - (biscuitWidth / 2.0f);
 biscuitMinY = biscuitPositionY - (biscuitHeight / 2.0f);
 biscuitMaxX = biscuitPositionX + (biscuitWidth / 2.0f);
 biscuitMaxY = biscuitPositionY + (biscuitHeight / 2.0f);
 isOverBiscuit = false;
 isBiscuitPressed = false ; 
 
 imageMode(CORNER);

  loadVideo();
   
  savedTime = millis();
  

}

 public void draw()
{
  background(0xFFF9DEE8);
 
  ps.addParticle();
  ps.run();

  
  drawTitre();
  drawPapier();
  drawWord();
      

  timeNow = millis();
  timeElapsed = (timeNow - timeLast) / 1000.0f * timeScale;
  timeLast = timeNow;


  if (isTimelineActive)
  {  
    timelinePlayhead += timeElapsed;

    if (timelinePlayhead >= timelineDuration)
    {

     timelinePlayhead -= timelineDuration;
    }
  }


  timelinePlayheadPosition = timelinePlayhead / timelineDuration * timelinePositionDelta + timelinePositionStartX;
  float alpha = timelinePlayheadPosition/4;
  
 
  stroke(255);
  strokeWeight(10);
  line(timelinePositionStartX, timelinePositionStartY, timelinePositionEndX, timelinePositionEndY);

  
  stroke(255);
  strokeWeight(12);
  line(timelinePositionStartX, timelinePositionStartY - timelineMarkerHalfSize, timelinePositionStartX, timelinePositionStartY + timelineMarkerHalfSize);

  
  stroke(255);
  strokeWeight(12);
  line(timelinePositionEndX, timelinePositionEndY - timelineMarkerHalfSize, timelinePositionEndX, timelinePositionEndY + timelineMarkerHalfSize);

 
  stroke(255,128,172,alpha);
  strokeWeight(20);
  line(timelinePlayheadPosition, timelinePositionStartY - timelineMarkerHalfSize, timelinePlayheadPosition, timelinePositionStartY + timelineMarkerHalfSize);

  
  textSize(30);
  fill(0xFFFF468A);
  text("Indice de chance", width/2, height - height/4 + 20);
  fill(255);
  text("Peu élevé" , 120, height - height/4+20);
  text("Très élevé ", 960, height - height/4+20);     
      
      
  if(showBiscuit && !isBiscuitPressed) {
    drawBiscuit02();
  }
  

  if (mouseX >= biscuitMinX && mouseX <= biscuitMaxX) {

    if (mouseY >= biscuitMinY && mouseY <= biscuitMaxY)
    {
      isOverBiscuit = true;
    }
    else
      isOverBiscuit = false;
  }
  else
    isOverBiscuit = false;


  if (isBiscuitPressed == true)
  {

   drawBiscuitOuvert();

  }
  else if (isOverBiscuit == true) 
  {

    drawBiscuit01();
    cursor(HAND); 
    
  }
  else 
  {
    cursor(CROSS);
  }


  int passedTime = millis() - savedTime;
  
  if (passedTime > totalTime) {
    savedTime = millis(); // Save the current time to restart the timer!
    playVideo = false;
  }
  
  if(playVideo) {
    image(intro, 0, 0); 
  }
  

if(keyPressed) {
  if (key == 'f' || key == 'F') {
      if (fantasySong.isPlaying()) {
        fantasySong.pause();
      } else {
        fantasySong.play();
      }
    }
   } 
}


 public void movieEvent(Movie intro) {
  intro.read();
}


 public void readConfig() {
  json = loadJSONObject("config.json");

  videoFile = json.getString("videoFile");
  musicFile = json.getString("musicFile");
  audioFile01 = json.getString("audioFile01");
  audioFile02 = json.getString("audioFile02");
  audioFile03 = json.getString("audioFile03");

  
}


 public void drawPapier() {
  fill(255);
  rectMode(CENTER);
  rect(width/2,950,800,120); 
}

 public void drawBiscuit01 () {
   image(imgBiscuitFortuneGauche, 275, 350);
   image(imgBiscuitFortuneDroite, 430,400);
}

 public void drawBiscuit02 () {
   image(imgBiscuitAmourGauche, 275, 350);
   image(imgBiscuitAmourDroite, 430,400);     
}

 public void drawBiscuitOuvert () {
   pushMatrix();
   translate(-100,0);
   image(imgBiscuitFortuneGauche, 275, 350);
   translate(200,0);
   image(imgBiscuitFortuneDroite, 430,400);
   popMatrix();
}


 public void drawWord () {
    fill(0xFFE5AA07);
    text(currentWord, width/2, 950);
}
  
 public void drawTitre() {
  // chargement du fichier en mémoire
  pushMatrix();  
  rotate(PI/60);
  scale(0.8f);
  image(imgTitre,180, height/9);
  filter(ERODE);
  popMatrix();
}


 public void loadVideo() {
  intro = new Movie(this, videoFile);
  intro.play();
  AudioAmour.play();
}



 public void mousePressed() {
  if (isOverBiscuit == true && (mouseButton == LEFT || mouseButton == RIGHT)) {
      isBiscuitPressed = true;
    
      int index = PApplet.parseInt(random(words.length));  
      currentWord = words[index];
    
      AudioCarriere.play();
      
      showOpenedBiscuit();
  }
}



 public void showOpenedBiscuit() {
    isBiscuitPressed = true;
    TimerTask task = new TimerTask() {
        public void run() {
         isBiscuitPressed = false; 
        }
    };
    
    Timer timer = new Timer("Timer");
    
    int delay = 2000;
    timer.schedule(task, delay);
}



 public void keyPressed()
{
  if (keyCode == UP)
    timeScale = constrain(timeScale + timeScaleDelta, timeScaleMin, timeScaleMax);
  if (keyCode == DOWN)
    timeScale = constrain(timeScale - timeScaleDelta, timeScaleMin, timeScaleMax);
  if (key == ENTER || key == RETURN)
  saveFrame("ma chance.jpg");
  
   if (keyCode == ' ')
    isTimelineActive = !isTimelineActive;
    
    if (keyCode == ' ')
    AudioFortune.play();   

}
 
class Particle {
  
  int colorDiffuse;
  
  PVector position;
  PVector velocity;
  PVector acceleration;
  float lifespan;

  Particle(PVector l) {
    acceleration = new PVector(0, 0.04f);
    velocity = new PVector(random(-1, 1), random(-2, 0));
    position = l.copy();
    lifespan = 255.0f;
    colorDiffuse = color(random(255),random(255),random(255));
  }

   public void run() {
    update();
    display();
  }

  // Method to update position
   public void update() {
    velocity.add(acceleration);
    position.add(velocity);
    lifespan -= 1.0f;
  }

  // Method to display
   public void display() {
    noStroke();
    fill(colorDiffuse, 127);
    ellipse(position.x, position.y, 5, 5);
  }

  // Is the particle still useful?
   public boolean isDead() {
    if (lifespan < 0.0f) {
      return true;
    } else {
      return false;
    }
  }
}
class ParticleSystem {
  ArrayList<Particle> particles;
  PVector origin;

  ParticleSystem(PVector position) {
    origin = position.copy();
    particles = new ArrayList<Particle>();
  }

   public void addParticle() {
    particles.add(new Particle(origin));
  }

   public void run() {
    for (int i = particles.size()-1; i >= 0; i--) {
      Particle p = particles.get(i);
      p.run();
      if (p.isDead()) {
        particles.remove(i);
      }
    }
  }
}


  public void settings() { size(1080, 1080); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "TP2KathyPoirier" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
